### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by Sheldonsuckz** [ligongcheng/qq_music_downloader#4]
Hello I'm back and this time using a VPN like you suggested.
Using the V2 script resulted in a timeout error.
Here is the log:
输入数字，1歌单、2单曲：2
输入qq歌曲id例如 002u0fTY2HoJJp :003cEz0o0ogtT4
timeout retry
timeout retry
timeout retry
timeout retry
timeout retry
error Again
Traceback (most recent call last):
  File "music.v2.py", line 116, in <module>
    save_song(url, singer, name, lrc)
  File "music.v2.py", line 31, in save_song
    if resource.status_code != 200:
AttributeError: 'NoneType' object has no attribute 'status_code'

**Comment by StrollStars** [comment]
同楼上，希望作者能够更新一下。

**Comment by joyven** [comment]
File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1068eb990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

这个超时了怎么解决？

**Comment by zheyiyuezhuo** [comment]
我是这样：
输入数字，1歌单、2单曲：2
输入qq歌曲id例如 002u0fTY2HoJJp :0008b7I13pBK76
Traceback (most recent call last):
  File "music.v2.py", line 110, in <module>
    name = res['name']
TypeError: string indices must be integers
